# Use of Force

```{r setup-7, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r load-libraries-7}
# Load necessary libraries

# Reading and wrangling
library(googlesheets4)
library(readr)
library(tidyverse)
library(janitor)
library(lubridate)
library(DT)

# Plotting
library(ggplot2)
library(RColorBrewer)

# Tables
library(kableExtra)

# Load custom function
source("function_clean_facility_names.R", local = knitr::knit_global())
```

```{r read-data-324-incident-7}
# Read Google Sheet incident worksheet, convert to data frame, and wrangle
df_324_inc <- read_sheet("https://docs.google.com/spreadsheets/d/1im5VSi3bIEi13O8WQ56wEIXSyNEstbGMylXXgD9bAG0/edit#gid=1858227071",
                 sheet="G-324A-19-inc",
                 col_types = "c") %>% 
  clean_names() %>%
  
  # Run custom cleaning function
  clean_facility_names() %>% 


  # df_specific changes
  unite(date, year:month) %>% 
  mutate(facility = as.factor(facility),
         state = as.factor(state),
         date = ym(date)
         ) %>% 
  mutate_at(c(6:76), as.numeric)
```


## Summary Tables

```{r}
df_force <- df_324_inc %>%
  
  # Subset the df to only the used cols
  select(id, facility, date,
       immediate_use_of_force_incidents:
       strip_searches
       ) %>% 
  
  # Need the rowwise function to compute a row-at-a-time
  # in the following mutate function
  rowwise(id) %>% 
  
  # Create a new total column
  mutate(total_use_of_force = sum(c_across(
       immediate_use_of_force_incidents:
       strip_searches
  ))) %>% 

  # Call a range of table columns and pivot long
  pivot_longer(.,
               cols=  immediate_use_of_force_incidents:total_use_of_force,
               names_to = "use_of_force_type",
               values_to = "use_of_force_count") %>%
  
  # Remove NA values
  drop_na() %>% 
  
  # Explicitly define factors
  mutate(use_of_force_type = factor(use_of_force_type, levels = c(
    "immediate_use_of_force_incidents",
    "calculated_use_of_force_incidents",
    "uses_of_force_with_chemical_agents",
    "incidents_where_non_lethal_weapons_were_used",
    "number_of_times_4_5_point_restraints_were_used",
    "use_of_force_with_serious_injury",
    "strip_searches",
    "total_use_of_force"
  )))
```

```{r}
df_force %>% 
  group_by(use_of_force_type) %>% 
  summarise(`Total Use of Force by Type` = sum(use_of_force_count)) %>% 
  ungroup() %>% 
  kable(caption = "Total Use of Force by Type",
        col.names = c("Use of Force Type", "Total Use of Force Type")) %>% 
  kable_styling(c("hover", "striped", "condensed", "responsive"))


df_force %>% 
  group_by(facility) %>% 
  summarise(total_use_of_force = sum(use_of_force_count)) %>% 
  arrange(desc(total_use_of_force)) %>% 
  ungroup() %>% 
  kable(caption = "Total Use of Force by Facility",
        col.names = c("Facility", "Total Use of Force by Facility")) %>% 
  kable_styling(c("hover", "striped", "condensed", "responsive")) %>% 
  scroll_box(height = "300px")
```

## Facet Plot of Use of Force by Facility

```{r use-force-facet, fig.height=40}
# Generating a linetype vector for use in the plot
plot_lines <- c(
    "solid",
    "solid",
    "solid",
    "solid",
    "solid",
    "solid",
    "solid",
    "dotted"
    )

# Use Color Brewer to set colors and modify
# the last color to be black for totals.
plot_colors <- brewer.pal(8, "Paired")
plot_colors[8] <- "#000000"

# Create plot labels
plot_labels <- c(
    "Immediate Use of Force Incidents",
    "Calculated Use of Force Incidents",
    "Uses of Force with Chemical Agents",
    "Incidents Where Non-Lethal Weapons Were Used",
    "Times 4/5 Point Restraints Used",
    "Use of Force With Serious Injury",
    "Strip Searches",
    "Total Disciplinary")

df_force %>% 
  
  # Calling the plot and formatting
  ggplot(aes(x=date, y = use_of_force_count, linetype=use_of_force_type))+
  geom_line(aes(color = use_of_force_type), size = .65) +
  
  # setting the linetype
  scale_linetype_manual(
    values = plot_lines,
    labels = plot_labels,
    name = "Use of Force Type:",
    guide = guide_legend(nrow = 8)
    )+
  
  # Setting the color
  scale_color_manual(
  values = plot_colors,
  labels = plot_labels,
  name = "Use of Force Type:",
  )+

  labs(title = "Disciplinary")+
  ylab("Number of Disciplinary Infractions")+
  xlab("Date")+
  theme(
    strip.text = element_text(size = 8),
    legend.position = "bottom"
    )+

    # Set the legend to multiple rows
  guides(col = guide_legend(nrow =8))+
  
  # Wrap
  facet_wrap(~ facility, ncol=3)
```
