# Medical

```{r setup-9, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r load-libraries-9}
# Load necessary libraries

# Reading and wrangling
library(googlesheets4)
library(readr)
library(tidyverse)
library(janitor)
library(lubridate)
library(DT)

# Plotting
library(ggplot2)
library(RColorBrewer)

# Tables
library(kableExtra)

# Load custom function
source("function_clean_facility_names.R", local = knitr::knit_global())
```

```{r read-data-324-incident-9}
# Read Google Sheet incident worksheet, convert to data frame, and wrangle
df_324_inc <- read_sheet("https://docs.google.com/spreadsheets/d/1im5VSi3bIEi13O8WQ56wEIXSyNEstbGMylXXgD9bAG0/edit#gid=1858227071",
                 sheet="G-324A-19-inc",
                 col_types = "c") %>% 
  clean_names() %>%
  
  # Run custom cleaning function
  clean_facility_names() %>% 


  # df_specific changes
  unite(date, year:month) %>% 
  mutate(facility = as.factor(facility),
         state = as.factor(state),
         date = ym(date)
         ) %>% 
  mutate_at(c(6:76), as.numeric)
```

## Medical Observation

```{r medical-mental-observation-facet, fig.height=40}
# Generating a linetype vector for use in the plot
plot_lines <- c(
    "solid",
    "solid",
    "dotted"
    )

# Use Color Brewer to set colors
plot_colors <- brewer.pal(3, "Paired")
plot_colors[3] <- "#000000"

# Create plot labels
plot_labels <- c(
    "Detainees in Medical Observation",
    "Detainees in Mental Health Observation",
    "Total Individuals in Medical or Mental Health Observation")

df_324_inc %>%
  
  # Subset the df to only the used cols
  select(id, facility, date,
       detainees_in_medical_observation:
       detainees_in_mental_health_observation
       ) %>% 
  
  # Need the rowwise function to compute a row-at-a-time
  # in the following mutate function
  rowwise(id) %>% 
  
  # Create a new total column
  mutate(total_mental_medical_observation = sum(c_across(
       detainees_in_medical_observation:
       detainees_in_mental_health_observation
  ))) %>% 

  # Call a range of table columns and pivot long
  pivot_longer(.,
               cols=  detainees_in_medical_observation:total_mental_medical_observation,
               names_to = "medical_mental_observation_type",
               values_to = "medical_mental_observation_count") %>%
  
  # Remove NA values
  drop_na() %>% 
  
  # Explicitly set factor levels
  mutate(medical_mental_observation_type = factor(medical_mental_observation_type, levels = c(
    "detainees_in_medical_observation",
    "detainees_in_mental_health_observation",
    "total_mental_medical_observation"
  ))) %>% 
  
  # Calling the plot and formatting
  ggplot(aes(x=date, y = medical_mental_observation_count, linetype=medical_mental_observation_type))+
  geom_line(aes(color = medical_mental_observation_type),size=.65) +
  
  # Set the linetype
  scale_linetype_manual(
    values = plot_lines,
    labels = plot_labels,
    name = "Observation Type:",
    guide = guide_legend(nrow = 3)
    )+
  
  # Set the color
  scale_color_manual(values = plot_colors,
                     labels = plot_labels,
                     name = "Observation Type:",)+

  labs(title = "Medical and Mental Health Observation")+
  ylab("Number of Individuals in Observation")+
  xlab("Date")+
  theme(
    strip.text = element_text(size = 8),
    legend.position = "bottom"
    )+

  # Set the legend to multiple rows
  guides(col = guide_legend(nrow =3))+
  
  # Wrap
  facet_wrap(~ facility, ncol=3)
  
```

## Infections Disease

```{r infectious-disease-facet, fig.height=40}
# Generating a linetype vector for use in the plot
plot_lines <- c(
    "solid",
    "solid"
    )

# Use Color Brewer to set colors
plot_colors <- brewer.pal(2, "Paired")

# Create plot labels
plot_labels <- c(
    "Infectious Disease Reported",
    "Infectious Disease Confirmed")

df_324_inc %>%
  
  # Subset the df to only the used cols
  select(id, facility, date,
       infectious_disease_reported:
       infections_disease_confirmed
       ) %>% 
  
  # Need the rowwise function to compute a row-at-a-time
  # in the following mutate function
  rowwise(id) %>% 
  
  # # Create a new total column
  # # In this case not used
  # mutate(total_infections_disease_report_confirmed = sum(c_across(
  #      infectious_disease_reported:
  #      infections_disease_confirmed
  # ))) %>% 

  # Call a range of table columns and pivot long
  pivot_longer(.,
               cols=  infectious_disease_reported:infections_disease_confirmed,
               names_to = "infectious_disease_type",
               values_to = "infectious_disease_count") %>%
  
  # Remove NA values
  drop_na() %>% 
  
  # Explicitly define factor levels
  mutate(infectious_disease_type = factor(infectious_disease_type, levels = c(
    "infectious_disease_reported",
    "infections_disease_confirmed"
  ))) %>% 
  
  # Calling the plot and formatting
  ggplot(aes(x=date, y = infectious_disease_count, linetype=infectious_disease_type))+
  geom_line(aes(color = infectious_disease_type),size=.65) +
  
  # Set the linetype
  scale_linetype_manual(
    values = plot_lines,
    labels = plot_labels,
    name = "Category:",
    guide = guide_legend(nrow = 2)
    )+
  
  # Set the color
  scale_color_manual(values = plot_colors,
    labels = plot_labels,
    name = "Category:")+

  labs(title = "Infectious Diseases Reported and Confirmed")+
  ylab("Count")+
  xlab("Date")+
  theme(
    strip.text = element_text(size = 8),
    legend.position = "bottom"
    )+

  # Set the legend to multiple rows
  guides(col = guide_legend(nrow =3))+
  
  # Wrap
  facet_wrap(~ facility, ncol=3)
  
  
```

## Medical and Mental Health Referrals

```{r referrals-facet, fig.height=40}
# Generating a linetype vector for use in the plot
plot_lines <- c(
    "solid",
    "solid",
    "solid",
    "solid",
    "dotted"
    )

# Use Color Brewer to set colors
plot_colors <- brewer.pal(5, "Paired")
plot_colors[5] <- "#000000"

# Create plot labels
plot_labels <- c(
    "Outside Medical Referrals",
    "Detainees Transported to Off-Site Hospitals for Emergency Reasons",
    "Admissions to Off-Site Hospitals for Medical Reasons",
    "Admissions to Off-Site Hospitals for Mental Health Reasons",
    "Total Referrals")


df_324_inc %>%
  
  # Subset the df to only the used cols
  select(id, facility, date,
       outside_medical_referrals:
       admissions_to_off_site_hospitals_for_mental_health_reasons
       ) %>% 
  
  # Need the rowwise function to compute a row-at-a-time
  # in the following mutate function
  rowwise(id) %>% 
  
  # Create a new total column
  mutate(total_referrals = sum(c_across(
       outside_medical_referrals:
       admissions_to_off_site_hospitals_for_mental_health_reasons
  ))) %>% 

  # Call a range of table columns and pivot long
  pivot_longer(.,
               cols=  outside_medical_referrals:total_referrals,
               names_to = "referral_type",
               values_to = "referral_count") %>%
  
  # Remove NA values
  drop_na() %>% 
  
  # Explicitly define factor levels
  mutate(referral_type= factor(referral_type, levels = c(
    "outside_medical_referrals",
    "detainees_transported_to_off_site_hospitals_for_emergency_care",
    "admissions_to_off_site_hospitals_for_medical_reasons",
    "admissions_to_off_site_hospitals_for_mental_health_reasons",
    "total_referrals"
  ))) %>% 
  
  
  # Calling the plot and formatting
  ggplot(aes(x=date, y = referral_count, linetype=referral_type))+
  geom_line(aes(color = referral_type),size=.65) +
  
  # Set the linetype
  scale_linetype_manual(
    values = plot_lines,
    labels = plot_labels,
    name = "Referral Type:",
    guide = guide_legend(nrow = 5)
    )+
  
  # Set the color
  scale_color_manual(values = plot_colors,
    labels = plot_labels,
    name = "Referral Type:")+

  labs(title = "Medical and Mental Health Referrals")+
  ylab("Number of Referrals")+
  xlab("Date")+
  theme(
    strip.text = element_text(size = 8),
    legend.position = "bottom"
    )+

  # Set the legend to multiple rows
  guides(col = guide_legend(nrow =5))+
  
  # Wrap
  facet_wrap(~ facility, ncol=3)
```

## Sick Call Requests and Encounters

```{r}
df_sick_call <- df_324_inc %>%
  
  # Select a subset of columns to work with
  select(id,
         facility,
         date,
         sick_call_requests,
         sick_call_encounters) %>% 
  
  # Need the rowwise function to compute a row-at-a-time
  # in the following mutate function
  rowwise(id) %>% 
  
  # Create new total column
  mutate(total_sick_call = sick_call_requests,
         sick_call_encounters) %>% 
  
  # Tidy
  pivot_longer(.,
               cols= sick_call_requests:
         sick_call_encounters,
               names_to = "sick_call_type",
               values_to = "sick_call_count") %>% 
  
  # Remove NA
  drop_na() %>% 
  
  # Explicitly set factor levels
  mutate(sick_call_type = factor(sick_call_type, levels = c(
    "sick_call_requests",
    "sick_call_encounters",
    "total_sick_call"
  )))
```

```{r}
df_sick_call %>% 
  group_by(sick_call_type) %>% 
  summarise(`Total Sick Call by Type` = sum(sick_call_count)) %>% 
  ungroup() %>% 
  kable(caption = "Total Sick Call by Type",
        col.names = c("Type", "Total")) %>% 
  kable_styling(c("hover", "striped", "condensed", "responsive"))

df_sick_call %>% 
  group_by(facility) %>% 
  summarise(total_sick_call = sum(sick_call_count)) %>% 
  arrange(desc(total_sick_call)) %>% 
  ungroup() %>% 
  kable(caption = "Total Sick Call Requests/Encounters by Facility",
        col.names = c("Facility", "Total")) %>% 
  kable_styling(c("hover", "striped", "condensed", "responsive")) %>% 
  scroll_box(height = "300px")
```

```{r sick-calls, fig.height=40}
# Generating a linetype vector for use in the plot
plot_lines <- c(
    "solid",
    "solid",
    "dotted"
    )

# Use Color Brewer to set colors
plot_colors <- brewer.pal(3, "Paired")
plot_colors[3] <- "#000000"

# Create labels
plot_labels <- c(
    "Sick Call Requests",
    "Sick Call Encounters",
    "Total Sick Calls")

df_324_inc %>%
  
  # Subset the df to only the used cols
  select(id, facility, date,
       sick_call_requests:
       sick_call_encounters
       ) %>% 
  
  # Need the rowwise function to compute a row-at-a-time
  # in the following mutate function
  rowwise(id) %>% 
  
  # Create a new total column
  mutate(total_sick_calls = sum(c_across(
       sick_call_requests:
       sick_call_encounters
  ))) %>% 

  # Call a range of table columns and pivot long
  pivot_longer(.,
               cols=  sick_call_requests:total_sick_calls,
               names_to = "sick_call_type",
               values_to = "sick_call_count") %>%
  
  # Remove NA values
  drop_na() %>% 
  
  # Explicitly define factor levels
  mutate(sick_call_type = factor(sick_call_type, levels = c(
    "sick_call_requests",
    "sick_call_encounters",
    "total_sick_calls"
  ))) %>% 
  
  # Calling the plot and formatting
  ggplot(aes(x=date, y = sick_call_count, linetype=sick_call_type))+
  geom_line(aes(color = sick_call_type),size=.65) +
  
  # Set the linetype
  scale_linetype_manual(
    values = plot_lines,
    labels = plot_labels,
    name = "Sick Call Type:",
    guide = guide_legend(nrow = 3)
    )+
  
  # Set the color
  scale_color_manual(values = plot_colors,
    labels = plot_labels,
    name = "Sick Call Type:")+

  labs(title = "Sick Calls")+
  ylab("Number of Sick Calls")+
  xlab("Date")+
  theme(
    strip.text = element_text(size = 8),
    legend.position = "bottom"
    )+

  # Set the legend to multiple rows
  guides(col = guide_legend(nrow =3))+
  
  # Wrap
  facet_wrap(~ facility, ncol=3)
```

## Suicide Attempts and Watches

The following shows Suicide Attempts and Suicide Watches based on the status of the data as of `r Sys.Date()`. The numbers are subject to change.

```{r}
df_suicide <- df_324_inc %>%
  
  # Select a subset of columns to work with
  select(id,
         facility,
         date,
         suicide_attempts_or_self_harm,
         suicide_watches_constant_watch_mental_health_observation) %>% 
  
  # Need the rowwise function to compute a row-at-a-time
  # in the following mutate function
  rowwise(id) %>% 
  
  # Create new total column
  mutate(total_suicide = suicide_attempts_or_self_harm +
         suicide_watches_constant_watch_mental_health_observation) %>% 
  
  # Tidy
  pivot_longer(.,
               cols= suicide_attempts_or_self_harm:
               total_suicide,
               names_to = "suicide_type",
               values_to = "suicide_count") %>% 
  
  # Remove NA
  drop_na() %>% 
  
  # Explicitly set factor levels
  mutate(segregation_type = factor(suicide_type, levels = c(
    "suicide_attempts_or_self_harm",
    "suicide_watches_constant_watch_mental_health_observation",
    "total_suicide"
  )))
```

```{r}
df_suicide %>% 
  group_by(suicide_type) %>% 
  summarise(`Total Suicide Attempt or Watch by Type` = sum(suicide_count)) %>% 
  ungroup() %>% 
  kable(caption = "Total Suicide Attempt or Watch by Type",
        col.names = c("Type", "Total")) %>% 
  kable_styling(c("hover", "striped", "condensed", "responsive"))

df_suicide %>% 
  group_by(facility) %>% 
  summarise(total_suicide = sum(suicide_count)) %>% 
  arrange(desc(total_suicide)) %>% 
  ungroup() %>% 
  kable(caption = "Total Suicide Attempt or Watch by Facility",
        col.names = c("Facility", "Total")) %>% 
  kable_styling(c("hover", "striped", "condensed", "responsive")) %>% 
  scroll_box(height = "300px")
```

```{r suicide-facet, fig.height=40}

# Use Color Brewer to set colors and modify
# the last color to be black for totals.
plot_colors <- brewer.pal(2, "Paired")

# Create plot labels
plot_labels <- c(
      "Suicide Attempts or Self Harm",
      "Suicide Watches/Constant Watch/Mental Health Observation")

df_324_inc %>%
  
  # Subset the df to only the used cols
  select(id, facility, date,
       suicide_attempts_or_self_harm,
       suicide_watches_constant_watch_mental_health_observation
       ) %>% 
  drop_na() %>% 
 
  # Call a range of table columns and pivot long
  pivot_longer(.,
               cols=  c(suicide_attempts_or_self_harm,
       suicide_watches_constant_watch_mental_health_observation),
               names_to = "suicide_type",
               values_to = "suicide_count") %>% 
  
  # Remove NA values
  drop_na() %>% 
  
  # Explicitly define factor levels
  mutate(suicide_type = factor(suicide_type, levels = c(
    "suicide_attempts_or_self_harm",
    "suicide_watches_constant_watch_mental_health_observation"
  ))) %>% 
  
  # Calling the plot and formatting
  ggplot(aes(x=date, y = suicide_count))+
  geom_line(aes(color=suicide_type), size = .65) +
  
  # Set the color
  scale_color_manual(
    values = plot_colors,
    labels = plot_labels,
    name = "Type:"
    )+
  
  labs(title = "Suicide Attempts and Watches")+
  ylab("Number of Attempts or Watches")+
  xlab("Date")+
  theme(
    strip.text = element_text(size = 5),
    legend.position = "bottom"
    )+
  # Set the legend to multiple rows
  guides(col = guide_legend(nrow =5))+
  
  # Wrap
  facet_wrap(~ facility, ncol = 3)


```

## Hunger Strikes

```{r hunger-strike-summary}
df_324_inc %>%
  
  # Subset the df to only the used cols
  select(id, facility, date, hunger_strikes) %>% 

  group_by(facility) %>% 
  summarise(total_hunger_strike = sum(hunger_strikes)) %>% 
  arrange(desc(total_hunger_strike)) %>% 
  ungroup() %>% 
  kable(caption = "Total Hunger Strikes by Facility",
        col.names = c("Facility", "Total Hunger Strikes")) %>% 
  kable_styling(c("hover", "striped", "condensed", "responsive")) %>% 
  scroll_box(height = "300px")
```

```{r hunger-strike-facet, fig.height=40}
# Use Color Brewer to set colors and modify
# the last color to be black for totals.
plot_colors <- brewer.pal(2, "Paired")

df_324_inc %>%
  
  # Subset the df to only the used cols
  select(id, facility, date,
       hunger_strikes
       ) %>% 
  drop_na() %>% 
 

  # Calling the plot and formatting
  ggplot(aes(x=date, y = hunger_strikes))+
  geom_line(size = .65) +
  
  # scale_color_manual(
  #   values = plot_colors,
  #   labels = c(
  #     "Suicide Attempts or Self Harm",
  #     "Suicide Watches/Constant Watch/Mental Health Observation"
  #     ),
  #   name = "Type:"
  #   )+
  # 
  labs(title = "Hunger Strikes")+
  ylab("Number of Hunger Strikes")+
  xlab("Date")+
  theme(
    strip.text = element_text(size = 5),
    legend.position = "bottom"
    )+
  
  # Set the legend to multiple rows
  guides(col = guide_legend(nrow =5))+
  
  # Wrap
  facet_wrap(~ facility, ncol = 3)
```
