# Observations While Assembling Data

Observations made on the data as they accumulate are logged below.

## 28 May 2021

1.  Adelanto ICE Processing Center - East and West have identical data for 2020, but the numbers are different for 2019 with East being much lower than west. Craig checked the inspections and the numbers are different for East and West in 2019 while they are in fact the same for 2020. Note that 2020 is a remote inspection. However, it is significant that the two are comparable in one instance and not comparable in another case.

2.  Almance County Jail and Chase County Detention Center both seem to register blank for solitary. Craig suspects this is because there were not cases of solitary reported.

## 27 May 2021

One of the important early observations has to do with the naming of facilities. ICE is often inconsistent with facility naming and the names do often change over time. Both the changing of names and inconsistent naming conventions can cause confusion as well as error when tabulating results.

1.  The graphs for "**Adelanto ICE Processing Center - East**" and "**Adelanto ICE Processing Center - West**" are identical. This is consistent with information Craig recalls seeing in one of the inspections, that the numbers for the facilities are "merged" or combined.

    -   For facet graphing consider filtering. For analysis purposes may need to treat the two facilities as "merged"

2.  "**Adelanto ICE Processing Center West**" should be combined with "**Adelanto ICE Processing Center - West**". It appears that ICE is not consistently naming the facilities, in one case the name lacks a dash character which causes them to be graphed separately.

    -   The dash was added to Adelanto West.

3.  It would be good to check if there really two facilities in Almance County. There are entries listed for "**Almance County Detention Center**" and "**Almance County Jail**".

    -   Need to verify that these are in fact distinct facilities.

4.  "**Aurora ICE Processing Center II - Annex**" and "**Aurora II Annex**" should probably be combined. Need to check the inspections to verify.

    -   "**Aurora II Annex (CO) - Jan. 29, 2021"** was changed to "**Aurora ICE Processing Center II - Annex (CO) - Jan. 29, 2021**"