---
title: "Home"
author: "Nathan Craig"
date: "`r format(Sys.Date(), '%A %B %d, %Y')`"
output: 
    bookdown::html_document2: 
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
    code_download: true
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Background

This project involves putting into order and performing preliminary analysis of inspections related data released by Immigration and Customs Enforcement (ICE). In 2018, Congressional appropriations stipulated that "ICE is directed to make public all final detention facility inspection reports within 60 days of inspection" [@departme2017, 33]. As of July, 2021 ICE is not complying with this standing directive from Congress.

In 2018, ICE established a "[Facilities Inspection](https://www.ice.gov/detain/facility-inspections)" web page and began releasing documents back to May of that year. The website states that "ICE is posting all facility inspection reports submitted by the third-party contractor. The reports are posted below in chronological order within 60 days of inspection." For each "inspection report" ICE supplies two documents:

-   a G-324A form known as a Significant Incident Summary (SIS) and,
-   a cover letter by the inspections contractor The Nakamoto Group.[^1]

[^1]: The SIS form G-324 is generally 4-9 pages depending on the version. On the new longer forms, one page is always nearly completely redacted, and two pages are boilerplate definitions. Therefore, both forms contain fewer than 5 pages of information.

Both versions of the G-324A form state that "the following information [must be completed]{.ul} prior to the scheduled review dates" (underline in original) and that "[t]his form should be filled out by the facility prior to the start of any inspection."

Congress directed ICE to release "all final detention facility reports." ICE claims to post "all facility inspection reports," but instead ICE is posting SIS forms that must be filled out before inspectors even arrive at the facility. Facility inspection reports regularly run in excess of 150 pages. There are examples of complete inspections obtained by National Immigrant Justice Center (NIJC) through FOIA. Outside of those earlier FOIA requests, which required lengthy litigation by the NIJC to force compliance, ICE has released no inspection reports and is not complying with a Congressional mandate.

Though not in compliance, the SIS and cover letter forms do provide some information to the public. Unfortunately, data are siloed in individual pdf documents, many of which lack OCR, and presented in tables that are not commensurate with comparative analysis. This project seeks to retrieve data from these documents, clean and organize that information into a usable form, and supply it along with some preliminary analysis to the public.

# How the work was done

During the Summer of 2021, data from the SIS and inspection cover letters was compiled into a series of spreadsheets, note this work is still in progress. The impetus for the project was Nathan Craig who was interested in collating the data to examine them for trends, patterns, and anomalies. The work was performed by three students funded under a National Science Foundation grant awarded to Dr. Neil Harvey (NMSU) and Dr. Jeremy Slack (NMSU). The students who performed the work were Juan Becerra (Stanford), Avigail Turima Romo (Columbia), and Daniela Navarro Verdugo (CSSLO). The three students worked with Dr. Craig to develop a workflow for compiling individual SIS and inspection cover letters into a series of spreadsheets. These web pages, still in development, document those procedures.
