---
title: "Untitled"
author: "Nathan Craig"
date: "6/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(ggplot2)
```


```{r}
df <- tribble(
             ~Date, ~Detainees.placed.in.administrative.segregation, ~Detainees.placed.in.disciplinary.segregation, ~Detainees.placed.in.segregation.for.medical.reasons,
    "January-2020",                                              1L,                                            4L,                                                   0L,
   "February-2020",                                              0L,                                            7L,                                                   1L,
      "March-2020",                                              2L,                                            4L,                                                   1L,
      "April-2020",                                              1L,                                            3L,                                                   8L,
        "May-2020",                                             28L,                                            3L,                                                  32L,
       "June-2020",                                              1L,                                            1L,                                                   0L,
       "July-2020",                                              0L,                                            4L,                                                   0L,
     "August-2020",                                              0L,                                            4L,                                                   3L,
  "September-2020",                                              0L,                                            3L,                                                   1L,
    "October-2020",                                              4L,                                            9L,                                                   0L,
   "November-2019",                                              2L,                                            5L,                                                   0L,
   "December-2019",                                              2L,                                            6L,                                                   0L
  ) %>% 
  mutate(Date = my(Date)) %>% 
  pivot_longer(cols = c(Detainees.placed.in.administrative.segregation, 
                        Detainees.placed.in.disciplinary.segregation,
                        Detainees.placed.in.segregation.for.medical.reasons),
               names_to = "Segregation_Type", 
               values_to = "Count")

```




```{r}
df %>% 

  ggplot(aes(x=Date, y = Count, group = Segregation_Type))+
  geom_line(aes(color= Segregation_Type))+
  labs(title = "Reported Use of Solitary at Bristol County Jail and House of Correction",
       subtitle = "As reported in Facility SIS Form G-324A",
       caption = "Source: https://www.ice.gov/doclib/facilityInspections/bristolCoJail_SIS_11-18-2020.pdf")+
  ylab("Number of Individuals Palced in Solitary")+
  xlab("Date")+
  theme(
    strip.text = element_text(size = 8),
    legend.position = "bottom"
    )+
    scale_color_manual(
      values = c("green",
                 "red",
                 "blue"),
      name = "Solitary Type:",
      labels = c(
        "Administrative",
        "Disciplinary",
        "Medical")
      )
```

